spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../../.env[.properties]

  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.onzbfmwknjuskmwyqtgn}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

server:
  port: ${SERVER_PORT:8080}

openex:
  cors-origin: ${OPENEX_CORS_ORIGIN:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
